[project]
name = "sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.120.0",
    "google-generativeai>=0.8.5",
    "langgraph>=1.0.1",
    "pydantic-settings>=2.11.0",
    "uvicorn>=0.38.0",
]
